---
galaxy_info:
  author: Sergey Naumov
  description: 
  company: (optional)
  license: license (GPLv2, CC-BY, etc)
  min_ansible_version: 1.2

dependencies: []
  # List your role dependencies here, one per line. Only
  # dependencies available via galaxy should be listed here.
  # Be sure to remove the '[]' above if you add dependencies
  # to this list.
  
